spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/compose-postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      ddl-auto: update
storage:
  minio:
    url: http://localhost:9000
    bucket: catalog-rs-bucket
    access-key: minio-access-key
    secret-key: minio-secret-key