spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/compose-postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
storage:
  minio:
    endpoint: http://localhost:9000
    bucket: catalog-rs-bucket
    access-key: minio-root-user
    secret-key: minio-root-password
    public-endpoint: http://localhost:9000
app:
  version: 1.0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tagsSorter: alpha